# Assignment 4 - Classes and analyzing data from multiple files 

## Completing and Submitting the Assignment
- Follow the instructions to fill in the code in this jupyter notebook template to complete the assignment. 
- Places where you need to change or add something are denoted with **# TODO**

- Rename your completed version of this notebook so that your last and first name are filled in the file name
    - e.g "Garton_Michael_assignment4.ipynb"
- Export as a Python script .py file with the same filename:
    - e.g. "Garton_Michael_assignment4.py
- Upload both .ipynb and .py files to Quercus Assignment 4.

## Setup (1 mark)
1. Download the .zip of data files from Quercus or here (http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip) and extract the /data/ folder and all of it's contents **into to the same folder as you downloaded this notebook**. **(0.5 marks)**

This is required and will make sure all relative paths are the same across student submissions when marking. 
It should have this structure
```
main_directory
│   last_first_assignment4.ipynb
│   last_first_assignment4.py # a copy of the .ipynb exported as a script
│
│   # you can have other things in this folder, the key thing is data/ is in the same directory as your .ipynb and .py
│
└───data/
│   │   inflammation-01.csv
│   │   inflammation-01.csv
│   │   ...
│   │   inflammation-12.csv
│   │   small-01.csv
│   │   small-02.csv
│   │   small-03.csv
│
```

## 1. Reading in our files and analyzing the data (2.5 marks)

We want to read in data from an arthritis study that followed 60 patients in a longitudinal study. This happened 12 times over the course of the study, resulting in 12 different data files. 

a. Make a list of **only** the .csv file paths that start with `inflammation` using `glob.glob()` and store in a variable named `fnames`. **(0.5 marks)**

In [239]:
#import glob
import glob

#only csv path with word inflammation, stored in fnames
fnames = glob.glob('data/inflammation*.csv')
print(fnames)  #print statement

['data/inflammation-05.csv', 'data/inflammation-11.csv', 'data/inflammation-10.csv', 'data/inflammation-04.csv', 'data/inflammation-12.csv', 'data/inflammation-06.csv', 'data/inflammation-07.csv', 'data/inflammation-03.csv', 'data/inflammation-02.csv', 'data/inflammation-01.csv', 'data/inflammation-09.csv', 'data/inflammation-08.csv']


# import libraries we will use 
import glob
import numpy as np

# TODO: fix this line to solve (a) 
fnames = glob.glob('data/inflammation*.csv')

# right now it includes all .csv files including small-xx.csv which we don't want
fnames.sort() # this just sorts them alphabetically
print(fnames) # confirm only inflammation files listed


b. Read in the first file in that list using `np.loadtxt()`, providing a filename and specifiying the `delimiter=','` and store in the variable `dt`. **(0.5 marks)**

# TODO: (b)
dt = np.loadtxt(fnames[0], delimiter= ',')

In [227]:
#import glob and numpy
import glob
import numpy as np

#use glob to find pattern and then sort in fnames
fnames= (glob.glob('data/inflammation*.csv'))

#find only inflamation.csv files
fnames.sort()
print(fnames)

#find number of .csv only files 
f_count = len(fnames)

#use if statement to find the # of .csv files, or print else statement
if f_count > 0:
    dt = np.loadtxt(fnames[0], delimiter= ',') #find first file of .csv type only, inflammation-05.csv, file not in numerical order
    print(dt)
else:
    print('There are no .csv files.')  #else statement if no .csv files found

['data/inflammation-01.csv', 'data/inflammation-02.csv', 'data/inflammation-03.csv', 'data/inflammation-04.csv', 'data/inflammation-05.csv', 'data/inflammation-06.csv', 'data/inflammation-07.csv', 'data/inflammation-08.csv', 'data/inflammation-09.csv', 'data/inflammation-10.csv', 'data/inflammation-11.csv', 'data/inflammation-12.csv']
[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


c. Define a function `patient_summary()` that summarizes the data using either "mean", "max" or "min" across patients **(0.5 marks)**
  - `patient_summary(data, operation)` should take a numpy array of data from our files, as well as a string ("mean", "max" or "min") describing what operation to use summarize the data over the course of the 40 days across **each patient**.
  - note: the shape of the output should be the same size as the number of patients (i.e. 60)


def patient_summary(data, operation):
    # TODO: specify the axis, 0 or 1
    ax = 
    
    # TODO: fill in the rest of the if(and or elif/else) statements
   #define patient_summary to summarize mean, max, min across each patient
def patient_summary(data, operation):  
    
    #use if statement with the appropriate string
    if operation == 'mean':
        summary_values = data.mean(axis=1)  #mean for each patient
    elif operation == 'max':
        summary_values = data.max(axis=1)  #max for each patient
    elif operation == 'min':
        summary_values = data.min(axis=1)  #min for each patient
    else: 
        raise ValueError ('Invalid opeation. Please choose mean, max or min.') #will return invalid if operations don't match
    return summary_values


In [228]:
import numpy as np  #import numpy

#define patient_summary to summarize mean, max, min across each patient
def patient_summary(data, operation):  
    
    #use if statement with the appropriate string
    if operation == 'mean':
        summary_values = data.mean(axis=1)  #mean for each patient
    elif operation == 'max':
        summary_values = data.max(axis=1)  #max for each patient
    elif operation == 'min':
        summary_values = data.min(axis=1)  #min for each patient
    else: 
        raise ValueError ('Invalid opeation. Please choose mean, max or min.') #will return invalid if operations don't match
    return summary_values

#get data from our files
dt = np.loadtxt(fnames[0], delimiter= ',')
print(f"The name of the first file is {fnames[0]}") 

#call the function patient_summary to calculate mean, min, max
summary_mean = patient_summary(dt, 'mean')
summary_max = patient_summary(dt, 'max')
summary_min = patient_summary(dt, 'min')

#print output for mean, min, max for each patient
print('The mean summary for each patient is:', summary_mean)
print('The max summary for each patient is:', summary_max)
print('The min summary for each patient is:', summary_min)

The name of the first file is data/inflammation-01.csv
The mean summary for each patient is: [5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]
The max summary for each patient is: [18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]
The min summary for each patient is: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# test it out on the data file we read in and make sure the size is what we expect
dt_min = patient_summary(dt, 'min')
print(len(dt_min))

In [229]:
dt_min = patient_summary(data, 'min')
print(len(dt_min))

dt_max = patient_summary(data, 'max')
print(len(dt_max))

dt_mean = patient_summary(data, 'mean')
print(len(dt_mean))

60
60
60


Sometimes, data entry results in some errors. We can programmatically screen for certain errors. 

For example, if a patient has a mean inflammation of 0, this may indicate a healthy individual was misgrouped into this dataset, or some other issue requiring further attention. 

d. Define a function, `detect_problems()` that can check for issues that may have come from data input errors **(1 mark)**
   - `detect_problems(data)` should take a numpy array of the data from one of our experiment files
   - we created a helper function `check_zeros(x)` that returns True or False if there are values of zero in an array
   - combine the results of `patient_summary()` with our helper function `check_zeros()` to create your new `detect_problems()` function
   - return True or False depending whether a problem was found. 

# Run this cell so you can use this premade helper function to do the check 
# for values in an array that equal 0, DO NOT MODIFY THIS CODE
def check_zeros(x):
    '''
    Given an array, x, check whether any values in x equal 0.
    Return True if any values found, else returns False.
    '''
    # np.where() checks every value in x against the condition (x == 0) 
    # and returns a tuple of indices where it was True (i.e. x was 0)
    flag = np.where(x == 0)[0] 
    
    # We can check if there are any objects in flag (i.e. not empty)
    # If not empty, it found at least one zero, so flag is True. And vice-versa.
    flag = len(flag) > 0
    
    return flag

It is not necessary to understand all the code inside the helper function, but when using code others have written, you should have a good idea of:
1. what goes IN the function (x, an array of numbers) 
2. what comes OUT of the function (True or False) 
3. what the output means (True if 0 found in array, False if no 0 found).

# example usage of check_zeros
values_0 = np.array([12,0,8,9,1])
values_1 = np.array([1,1,1,1,1])

print(check_zeros(values_0))
print(check_zeros(values_1))

In [230]:
def check_zeros(x):
    # np.where() checks every value in x against the condition (x == 0) 
    # and returns a tuple of indices where it was True (i.e. x was 0)
    flag = np.where(x == 0)[0] 
    
    # We can check if there are any objects in flag (i.e. not empty)
    # If not empty, it found at least one zero, so flag is True. And vice-versa.
    flag = len(flag) > 0
    
    return flag

In [231]:
#import nupmy
import numpy as np 

#define function: detect_problems 
def detect_problems(data):
    means = patient_summary(data, 'mean')  #calculate the mean inflammation value for each patient

#Find True in the helper function check_zeroes or 0 value in the mean inflammation
    if check_zeros(data) or (means == 0).any(): #if any of these have a 0 value
        return True  #output True, problem found
    else:
        return False  #output False, no problems
    
#get data from our files
data = np.loadtxt(fnames[0], delimiter= ',')

#go through files and find problems 
problem_found = detect_problems(data)
print(problem_found)

#output the result
if problem_found:
    print('Data entry results in some errors')
else:
    print('No errors found in data entry results')

True
Data entry results in some errors


In [232]:
#example usage
values_0 = np.array([12,0,8,9,1])
values_1 = np.array([1,1,1,1,1])

print(check_zeros(values_0))
print(check_zeros(values_1))

True
False


# TODO: Define your function `detect_problems` here 
# using patient_summary() to get the means and check_zeros() to check for zeros in the means






## 2. Creating an experiment class (4.5 marks)

Let's store our experiments in a class. Each instance will be ONE experiment consisting of measurements from 60 patients over 40 days in the arthritis and inflammation study:
- Each instance object comes from one of the 12 sessions i.e. one `Experiment()` = one data file/data collection period.
- We can also bundle all the functions we've made above that operate on these data files into one class.

Modify the cell below to accomplish the following:

a. Create two **class attributes** named **study** to store the string "arthritis", and another named **experimenter** to store the string "Dr. Aria" **(1 mark)**  
b. Define a new method `add_data()` that reads in a .csv and stores the result in the pre-existing .data attribute that was made during `__init__()`. Don't forget the delimiter. **(1 mark)**  
c. Define a new method `patient_summary(self, operation)`. It is the same as the one we have already written, BUT it does not take `data` as an argument anymore (but still takes `operation`). The method reads from an instance's state to access what is in `.data`. It should still return summary values per patient for the given operation. **(1 mark)**

# TODO: modify this basic class as per the instructions above
class Experiment:
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None


In [233]:
import numpy as np #import numpy

class Experiment:
    study = "arthritis" #class attribute of string
    experimenter = "Dr. Aria" #class attribute of string
        
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
        
    def add_data(self, filename):  #defining new method
        self.data = np.loadtxt(filename, delimiter= ',') #reads .csv and stores in a .data attribute
        
    def patient_summary(self, operation):  #defining new method
        if self.data is None:
            raise ValueError("Data not loaded. Please add data using add_data()")  #error message without using loading data first
        if operation == 'mean':
            summary_values = self.data.mean(axis=1)  #mean for each patient
        elif operation == 'max':
            summary_values = self.data.max(axis=1)  #max for each patient
        elif operation == 'min':
            summary_values = self.data.min(axis=1)  #min for each patient
        else:
            raise ValueError("Invalid operation. Please choose 'mean', 'max', or 'min'")
        return summary_values  #return summary values per patient for the given operation

**Putting it all together.** 

d. Loop over `fnames` created earlier with all the `inflammation-xx.csv` files and create one instance of the Experiment() class per file. These do not need to be stored beyond inside the loop (e.g. we don't need to save all the Experiments in a list). Only print the filenames where the data was flagged in that experiment. **(1.5 marks)** 

We have written the code for you, but you need to move them around to make the code functional (including adding indents where necessary).

Note: We can assume that the filenames are ordered such that they reflect the order of data collection (e.g. inflammation-01.csv is session # 1).



# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

print(f) # print filename
exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
session_counter += 1 # increment our counter to the next session number
if check_zeros(values): # check whether any 0s in our means
session_counter = 1 # initialize counter
exp.add_data(f) # read in our data to our experiment
for f in fnames: # iterate over data files
values = exp.patient_summary("mean") # get our patient means


In [234]:
session_counter = 1 # initialize counter
for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        session_counter += 1 # increment our counter to the next session number
        print(f) # print filename

data/inflammation-03.csv
data/inflammation-08.csv
data/inflammation-11.csv


## Finishing Up
1. Rename this file if you haven't already replacing the words in the filename with your actual last and first name
2. Export as a .py and submit BOTH .ipynb and .py files
3. Make sure you haven't changed any variable names we specifically asked you to define as such. 

*Markdown* and LaTex: 𝛼²
